### ISSUE TITLE
Font Copyright Concern

### ISSUE THREAD

**Issue by 1998code** [openai/openai-quickstart-node#131]
### Describe the feature or improvement you're requesting

Hello @jeevnayak / @logankilpatrick,

Wendy from Process Type Foundry asked us (the developers) who fork/use this project to pay them $39 for ColfaxAI font licensing. 

Is it scamming? Did OpenAI get the proper license for it?
I am confusing 🫤

**Comment by 1998code** [comment]
Related to these lines inside [pages/index.module.css](https://github.com/openai/openai-quickstart-node/blob/master/pages/index.module.css)

```css
@font-face {
  font-family: "ColfaxAI";
  src:
    url(https://cdn.openai.com/API/fonts/ColfaxAIRegular.woff2) format("woff2"),
    url(https://cdn.openai.com/API/fonts/ColfaxAIRegular.woff) format("woff");
  font-weight: normal;
  font-style: normal;
}

@font-face {
  font-family: "ColfaxAI";
  src:
    url(https://cdn.openai.com/API/fonts/ColfaxAIBold.woff2) format("woff2"),
    url(https://cdn.openai.com/API/fonts/ColfaxAIBold.woff) format("woff");
  font-weight: bold;
  font-style: normal;
}
```
